server:
  port: 8030
spring:
  data:
      mongodb:
        uri: mongodb://localhost:27017/bezkoder_db/personalCustomer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
