server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customerservice
          uri: lb://customerservice
          predicates:
          - Path=/rest/personalCustomer/**
        - id: bankaccountservice
          uri: lb://bankaccountservice
          predicates:
          - Path=/rest/bankAccount/**
        - id: creditservice
          uri: lb://creditservice
          predicates:
          - Path=/rest/credit/**
        - id: transactservice
          uri: lb://transactservice
          predicates:
          - Path=/rest/transact/**